[toolchain]

[features]
skip-lint = false
seeds = false

[programs.localnet]
test_sol_token_pg = "BtrNTqruuMtwDqWd8ChBx5ckXYmdWuoeFEaYbwp5TasW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/evergreen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -b"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 
program = "./tests/fixtures/metadata.so"